spring.application.name=blackjack

spring.data.mongodb.uri=mongodb://localhost:27017/blackjack
spring.data.mongodb.database=blackjack

spring.r2dbc.url=r2dbc:mysql://localhost:3306/blackjack
spring.r2dbc.username=blackjack_user
spring.r2dbc.password=blackjack_pass

spring.sql.init.mode=always

logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.mysql=DEBUG