spring.application.name=blackjack

# MongoDB: Use the environment variable if present, otherwise fallback to localhost
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/blackjack}
spring.data.mongodb.database=blackjack

# R2DBC: Use the environment variable if present, otherwise fallback to localhost
spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/blackjack}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:blackjack_user}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:blackjack_pass}

spring.sql.init.mode=always

logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.mysql=DEBUG